bugfix: Fix test_fp4_quantize test bug (#1585)
<!-- .github/pull_request_template.md -->

## 📌 Description

`test_fp4_quantize` currently has failures on SM100. This PR fixes those
failures by using a different unswizzling helper function. Separately,
I'd like to understand why there are multiple unswizzling helpers, but
to simplify things, I'm not refactoring in this PR.

I also changed the skip reasons in this test file to explicitly say that
there's a min CUDA version for NVFP4, because that was an issue I had in
my environment that wasn't immediately obvious from the current skip
reason.

## 🔍 Related Issues

None that I know of.

## 🚀 Pull Request Checklist

### ✅ Pre-commit Checks

- [ ✅ ] I have installed `pre-commit` by running `pip install
pre-commit` (or used your preferred method).
- [ ✅ ] I have installed the hooks with `pre-commit install`.
- [ ✅ ] I have run the hooks manually with `pre-commit run --all-files`
and fixed any reported issues.

## 🧪 Tests

I've tested with:

```
pytest -q 'tests/test_fp4_quantize.py'
```

Before (in internal CI): 
```
=========================== short test summary info ============================
FAILED tests/test_fp4_quantize.py::test_fp4_quantization[True-True-cuda:0-42-shape0-dtype0] - RuntimeError: shape '[1, 2, 1, 32, 4, 4]' is invalid for input of size 512
FAILED tests/test_fp4_quantize.py::test_fp4_quantization[True-True-cuda:0-42-shape0-dtype1] - RuntimeError: shape '[1, 2, 1, 32, 4, 4]' is invalid for input of size 512
FAILED tests/test_fp4_quantize.py::test_fp4_quantization[True-True-cuda:0-42-shape2-dtype0] - RuntimeError: shape '[1, 2, 1, 32, 4, 4]' is invalid for input of size 512
FAILED tests/test_fp4_quantize.py::test_fp4_quantization[True-True-cuda:0-42-shape2-dtype1] - RuntimeError: shape '[1, 2, 1, 32, 4, 4]' is invalid for input of size 512
========================= 4 failed, 49 passed in 6.83s =========================
```

After (local testing):

```
.....................................................                                                                           [100%]
53 passed in 0.77s
```

- [ ✅ ] Tests have been added or updated as needed.
- [ ✅ ] All tests are passing (`unittest`, etc.).

## Reviewer Notes

<!-- Optional: anything you'd like reviewers to focus on, concerns, etc.
-->