[chore] Fix CI pre-commit mypy error (#3040)
<!-- .github/pull_request_template.md -->

## 📌 Description

Fix CI pre-commit mypy error
``` bash
mypy.....................................................................Failed
- hook id: mypy
- exit code: 1

flashinfer/jit/core.py: note: In member "__init__" of class "JitSpecRegistry":
flashinfer/jit/core.py:164:9: note: By default the bodies of untyped functions are not checked, consider using --check-untyped-defs  [annotation-unchecked]
flashinfer/jit/core.py:165:9: note: By default the bodies of untyped functions are not checked, consider using --check-untyped-defs  [annotation-unchecked]
flashinfer/autotuner.py: note: In member "__init__" of class "AutoTuner":
flashinfer/autotuner.py:579:9: note: By default the bodies of untyped functions are not checked, consider using --check-untyped-defs  [annotation-unchecked]
flashinfer/autotuner.py:581:9: note: By default the bodies of untyped functions are not checked, consider using --check-untyped-defs  [annotation-unchecked]
flashinfer/comm/allreduce.py: note: In function "allreduce_fusion":
flashinfer/comm/allreduce.py:713:13: error: Missing positional arguments "quant_out", "scale_out", "routed_scaling_factor" in call to "trtllm_moe_finalize_allreduce_fusion"  [call-arg]
flashinfer/aot.py: note: In function "main":
flashinfer/aot.py:979:5: note: By default the bodies of untyped functions are not checked, consider using --check-untyped-defs  [annotation-unchecked]
Found 1 error in 1 file (checked 193 source files)
```

## 🔍 Related Issues

<!-- Link any related issues here -->

## 🚀 Pull Request Checklist

Thank you for contributing to FlashInfer! Before we review your pull
request, please make sure the following items are complete.

### ✅ Pre-commit Checks

- [x] I have installed `pre-commit` by running `pip install pre-commit`
(or used your preferred method).
- [x] I have installed the hooks with `pre-commit install`.
- [x] I have run the hooks manually with `pre-commit run --all-files`
and fixed any reported issues.

> If you are unsure about how to set up `pre-commit`, see [the
pre-commit documentation](https://pre-commit.com/).

## 🧪 Tests

- [x] Tests have been added or updated as needed.
- [x] All tests are passing (`unittest`, etc.).

## Reviewer Notes

<!-- Optional: anything you'd like reviewers to focus on, concerns, etc.
-->


<!-- This is an auto-generated comment: release notes by coderabbit.ai
-->
## Summary by CodeRabbit

* **Bug Fixes**
* Fixed an issue in MOE finalization to ensure correct parameter
handling during fused finalization steps, improving stability and
correctness of final outputs.
<!-- end of auto-generated comment: release notes by coderabbit.ai -->

---------

Signed-off-by: jiahanc <173873397+jiahanc@users.noreply.github.com>