bugfix: Fix crash when pos_encoding_mode is passed as int (#1413)
This PR is to fix this issue caused by
https://github.com/flashinfer-ai/flashinfer/commit/e608c38f5744fd4929608f5ccfe77f88cde471ec
```  
File "/scratch/repo/flashinfer/flashinfer/prefill.py", line 83, in get_fmha_module                                                                                                               pos_encoding_mode.value,                                                                                                                                                                       ^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                    AttributeError: 'int' object has no attribute 'value' 
```

Update get_fmha_module to expect pos_encoding_mode as an Enum instead of
an int; raises error otherwise.

cc @yzh119