bugfix: import wrapper of mla decode (#1013)
In `tests/test_mla_decode_kernel.py`, the code below uses
`BatchDecodeMlaWithPagedKVCacheWrapper`:


https://github.com/flashinfer-ai/flashinfer/blob/26bc6b31fa9f0a2daa4926049fa8154e3914c399/tests/test_mla_decode_kernel.py#L348-L355

However an AttributeError is thrown:

```
AttributeError: module 'flashinfer' has no attribute 'BatchDecodeMlaWithPagedKVCacheWrapper'. Did you mean: 'BatchDecodeWithPagedKVCacheWrapper'?
```

Because the module `flashinfer` does not import
`BatchDecodeMlaWithPagedKVCacheWrapper` from submodule `.decode` and
export it.

This patch can solve it.